### ISSUE TITLE
Checking if the character can pass the HP test of High dragons

### ISSUE THREAD

**Issue by RaenonX** [junlico/dragalia-lost#1]
Considering adding a function **checking that if the character can go into the High Dragons stages.**
For example, if I query the data of Vanessa, then I will have some field saying that I will be able to survive under what condition, maybe WP with EX of 8% def or 15% HP...etc. 

I went to Reddit and grab an excel of a parameter calculator excel which almost does the same thing of what the code of this repo does, then I decompose the formula it used to calculate the damage. [This image](https://i.imgur.com/squwEFQ.jpg) may help you to implement this HP checking function. 

The source link of this formula is stated in the image, you may go there and grab some information to make an extension for this code if you want.

----

I would be happy to help you implement this to your code, but because that I am currently a student, and the workload this quarter is relatively heavy, so I decided to create this issue instead of creating a pull request.

**Comment by junlico** [comment]
Thanks for your feedback.
This is feature is on my plan, will be implemented in next two updates.

**Comment by junlico** [comment]
DONE
