### ISSUE TITLE
sHZD HP Check

### ISSUE THREAD

**Issue by NoctisCepheus** [junlico/dragalia-lost#13]
There seems to be something off in the computation of xHZD's hp check.

Build:
Fleur 50MC 100HP
Merciful Claw 0UB 0HP
RR MUB 100HP
SS MUB 0HP
Cupid MUB

Halidom:
Altars 35
Dojo 31
Fafnir 0
Seabed 30
Sweet Retreat 26
Cricus Tent 0

Additional Stats:
Def 30%

With all this, my Fleur's HP would be 2381 and would survive sHZD's hp check according to the calculator. But during my runs, i never survive the opening blast of sHZD

**Comment by NoctisCepheus** [comment]
Also, can i leave a suggestion.
1. Have the ability to save builds locally so we can go back and look at previous builds even after closing the window.
2. Sharing builds even just as an image of the list of the equipments and augments. Or a link in itself so after sharing, the receiver can play around it as well. Just like other build simulators.

Thank you for the hard work!! The DL community appreciates it!!

**Comment by junlico** [comment]
5 / 3 * 7996 * 4.4 * 0.5 / ( 10 * (1 + 38%)) * 1.05 = 2230

This is expected maximum damage.
If you can't survive, maybe Euden uses his S2 late.
