### ISSUE TITLE
Inaccurate Might Calculations

### ISSUE THREAD

**Issue by vrwntrs** [junlico/dragalia-lost#14]
The might calculations are off in the calculator. The calculated might is higher than what I get in-game, causing a build I thought would pass might gates to fall very short.

**Comment by junlico** [comment]
Please provide in-game stats details and snapshots of the calculator details.
Thanks

**Comment by vrwntrs** [comment]
![Screenshot_20191118-105233](https://user-images.githubusercontent.com/57819677/69080799-7d2b9d00-09f1-11ea-83e3-a732377fe3c0.png)
![Screenshot_20191118-105124](https://user-images.githubusercontent.com/57819677/69080817-8452ab00-09f1-11ea-8dd5-1e5981a863f2.png)

As you can see, the strength and HP are accurate, but the might is almost 300 over the in-game number

**Comment by junlico** [comment]
Check the bonds of your dragon, the default value is 30 in the calculator.
If you didn't feed the dragon at all, the level is 1, so the might difference is 290.

**Comment by vrwntrs** [comment]
Oh, you're right. Sorry about that
