### ISSUE TITLE
%HP from dragons not calculated

### ISSUE THREAD

**Issue by katjang** [junlico/dragalia-lost#15]
Hey it seems that %HP does not get calculated from dragons, example:

Gleo automatic build (with shinobi)                   -> HP: 2507
Change dragon to Nidhogg (hybrid dragon)    ->  HP: 2517

this doesn't seem right (i want to plan my off-element memes please)!

**Comment by katjang** [comment]
Seems like the def boost from give me your wounded also does not work (may be intentional?)

**Comment by junlico** [comment]
fixed
