### ISSUE TITLE
Potential Bug in High Dragons HP Calculations

### ISSUE THREAD

**Issue by RaenonX** [junlico/dragalia-lost#2]
- Calculation for melee adventurers seems not having a 25% damage reduction (for example, applying Xainfred for HBrun)
- HP of `Thaniel with The Chocolatiers` seems to be correct (3099), but the result saying that it requires 3163 HP with DEF 20% (Thaniel's S2, data acquired from [here](https://dragalialost.gamepedia.com/Thaniel#Lv.%202) on. Maybe because of the unclear explanation of that *Damage* text. For me, the chance of death is around 2 of 10.

**Comment by junlico** [comment]
[Damage Formula](https://dragalialost.gamepedia.com/Damage_Formula)
Advanturer's DefCoef, melee is 10, range is 8.

**Comment by RaenonX** [comment]
I see, maybe consider adding this into the calculation?

Sent from Mail for Windows 10
