### ISSUE TITLE
Possible improvements

### ISSUE THREAD

**Issue by RaenonX** [junlico/dragalia-lost#3]
- Click on the entry instead of click on the icon to apply the certain object (adventurer, wyrmprint, weapon...etc.)
- Add text searching function instead of filters only to make users be easier to find objects as these things will only getting more and more.
- Have a clearer explanation about what "Damage" means in the high dragons HP calculation section. (Minimum or Maximum) Have both min. and max. stated would be great.
- More intuitive ways to exit the halidom configuration.
- *(improvement for mobile users)* Maybe a collapsible objects section (2nd section), or something that can reduce the scrolling-up-and-down time when applying items. For me, it takes too much time to apply all 4 objects.
- *(improvement for mobile users)* Better layout for the parameter section (1st section) as it extended outside of my screen while other sections don't.

Note: My phone is Galaxy Note 8, 1440x2960 pixels.

**Comment by junlico** [comment]
Thanks for your feedback.

**Comment by junlico** [comment]
with new version of calculator, majority of your advice achieved.

- I add filter feature on the icon, so still need click image to select.

- search bar: DONE.

- damage is clear stated as MIN & MAX

- For halidom configuration, isn't range input clear enough? Now, able to save config in localStorage.

- Implement scroll feature, also default equipments will be selected when adventurer is selected.

- optimize the layout.

Thanks again. :)
