### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by b1ueb1ues** [junlico/dragalia-lost#7]
the mc will automatelly change to 45 when you set ex to 4.

**Comment by junlico** [comment]
That's what I'm intended.
I don't think someone has 40 + 4 combinations honestly.
If active maximum co-abilities, 49 or 50 will be the result, right?

**Comment by b1ueb1ues** [comment]
why not 50?

**Comment by junlico** [comment]
If you want 50, directly change MC.
I didn't disable co-ability field when the MC was lower than 40. So if someone wants to level co-ability, it's helpful to change the MC to 45 automatically.
