### ISSUE TITLE
Possibly make HJP hp check for 1st electron burst instead of opening blast.

### ISSUE THREAD

**Issue by brimstone-** [junlico/dragalia-lost#8]
I think it'd be useful to add/replace the hp check calculator of HJP with the first electron burst as well as or instead of the opening.

This is because the true hp check of High Jupiter comes after the opening blast during the first electron burst.  This burst is usually much deadlier than the opening.  The subsequent electron bursts I think can do more damage but are typically tanked by dragon transformation when playing correctly.  It's quite possible to build a unit that survives the HJP opening but simply dies to the first electron despite full hp.

**Comment by junlico** [comment]
change multiplier to 4.8 for temp solution.
